## Travis CI Integration
language: csharp
solution: aspnet-mvc-ioc.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore aspnet-mvc-ioc.sln

script:
  - xbuild aspnet-mvc-ioc.sln
  - nunit-console lib/SimpleLogin.Test.dll
